### PR TITLE
fix: update file structure

### PR DESCRIPTION
**Pull request by kaushikjadhav01**

### CODE REVIEW

**Review by Surya-06 — COMMENTED** [review]
nit: Do we need the __init__.py file in the test folder?

**Comment by Surya-06** [comment]
Also, if the .gitignore file is generated then could you please leave a comment about the source so that we can add it later in the citations ?

**Review by Surya-06 — CHANGES_REQUESTED** [review]
Please consider the suggestions in the other comments before closing this one. Thanks!

**Comment by kaushikjadhav01** [comment]
> nit: Do we need the **init**.py file in the test folder?

Yes, without it, files in Code folder will not be reachable in test folder

**Comment by kaushikjadhav01** [comment]
> Also, if the .gitignore file is generated then could you please leave a comment about the source so that we can add it later in the citations ?

Yes, this was given by the TA only in discord, check links channel:
https://discord.com/channels/1009547855301718107/1009554620449816606/1011291376983478312

**Comment by Surya-06** [comment]
> > Also, if the .gitignore file is generated then could you please leave a comment about the source so that we can add it later in the citations ?
> 
> Yes, this was given by the TA only in discord, check links channel: https://discord.com/channels/1009547855301718107/1009554620449816606/1011291376983478312

Cool, I meant that we could have the link from the final destination handy since it's something that we pulled from a different location. Just something to have in the citations maybe.

**Comment by Surya-06** [comment]
> > nit: Do we need the **init**.py file in the test folder?
> 
> Yes, without it, files in Code folder will not be reachable in test folder

Oh, I think tried a similar thing earlier and it somehow passed so I was curious. This isn't anything blocking though so we should be alright.

**Review by Surya-06 — APPROVED** [review]

**Pull request merged**
